<a href="https://colab.research.google.com/github/AnshiM26/IEEE/blob/main/Heart_Disease_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Preprocessing


## Importing the dataset

In [191]:
import pandas as pd
import numpy as np
dataset=pd.read_csv('heart_disease_data.csv')
dataset.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [192]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [193]:
print(dataset.columns)

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')


## Dependent and independent feaures


In [194]:
X=np.array(dataset.drop(columns=['target'])) #independent features
y=np.array(dataset['target'])  #dependent feature - target

In [195]:
print(X)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]


In [196]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


##Splitting into Training set and Test set

In [197]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [198]:
print("Number of rows and columns in X_train:", X_train.shape)
print("Number of rows and columns in X_test:", X_test.shape)
print("Number of rows and columns in y_train:", y_train.shape)
print("Number of rows and columns in y_test:", y_test.shape)

Number of rows and columns in X_train: (242, 13)
Number of rows and columns in X_test: (61, 13)
Number of rows and columns in y_train: (242,)
Number of rows and columns in y_test: (61,)


# Feature Scaling


In [199]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [200]:
print(X_train)

[[-1.35679832  0.72250438  0.00809909 ...  0.95390513 -0.68970073
  -0.50904773]
 [ 0.38508599  0.72250438 -0.97189094 ...  0.95390513 -0.68970073
   1.17848036]
 [-0.92132724  0.72250438  0.98808912 ... -0.69498803 -0.68970073
  -0.50904773]
 ...
 [ 1.58263146  0.72250438  1.96807914 ... -0.69498803  0.32186034
  -0.50904773]
 [-0.92132724  0.72250438 -0.97189094 ...  0.95390513 -0.68970073
   1.17848036]
 [ 0.92942484 -1.38407465  0.00809909 ...  0.95390513  1.33342142
  -0.50904773]]


In [201]:
print(X_test)

[[ 2.76218225e-01  7.22504380e-01 -9.71890936e-01  1.16949120e+00
   5.53408401e-01 -3.83300706e-01 -1.04610909e+00 -1.70875171e+00
   1.47790748e+00 -3.75556294e-01 -6.94988026e-01  3.21860343e-01
  -2.19657581e+00]
 [ 4.93953764e-01  7.22504380e-01  1.96807914e+00  2.36038903e+00
   7.81171723e-01 -3.83300706e-01 -1.04610909e+00  3.98288831e-01
  -6.76632341e-01 -7.39094787e-01 -6.94988026e-01 -6.89700735e-01
   1.17848036e+00]
 [ 2.76218225e-01  7.22504380e-01  9.88089118e-01  1.16949120e+00
  -2.29363312e+00  2.60891771e+00  8.43132697e-01  1.02591793e+00
  -6.76632341e-01 -7.39094787e-01  9.53905134e-01  3.21860343e-01
   1.17848036e+00]
 [ 1.67350456e-01 -1.38407465e+00 -9.71890936e-01  2.16772932e-01
   3.07778522e+00 -3.83300706e-01 -1.04610909e+00 -5.18701733e-03
   1.47790748e+00  8.05943807e-01 -6.94988026e-01  1.33342142e+00
   1.17848036e+00]
 [ 1.80036700e+00 -1.38407465e+00  9.88089118e-01 -1.21230447e+00
   3.44625356e-01  2.60891771e+00 -1.04610909e+00 -9.01800013e-01


# Classification - model used- K-Nearest Neighbours

## K-Nearest Neighbours



In [202]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [203]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) #displalys the predicted values against the test values

[[0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]]


## Confusion Matrix and accuracy

In [204]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[27  2]
 [ 4 28]]


0.9016393442622951

## Predicting a New result

In [205]:
print(classifier.predict(sc.transform([[43,	0,	0,	132,	341,	1,	0,	136,	1,	3,	1,	0,	3]])))

[0]
